name: Tests Cron (Matrix)

on:
  #   schedule:
  #     - cron: '0 0 * * *'
  workflow_dispatch:

env:
  NODE_VERSION: "20"

jobs:
  test:
    name: Run tests (${{ matrix.browser }})
    uses: ./.github/workflows/tests.yml
    with:
      browser: ${{ matrix.browser }}
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        browser: [ chromium, firefox, webkit ]
